name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 Pillow numpy reportlab pynput pyautogui python-docx pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller SnapText.spec
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SnapText
        path: dist/SnapText.exe 
